### ISSUE TITLE
References

### ISSUE THREAD

**Issue by rossibarra** [rossibarra/angsdwrapper-poster#1]
Add in and format references throughout poster. Need references for papers using ANGSD (mosquite one from REHAB is an example), and formatting and \ref inserted throughout.

**Comment by SidBhadra-Lobo** [comment]
Ok

**Comment by SidBhadra-Lobo** [comment]
How many angsd papers, just one? In using the mosquito paper, do I add the
entire paper as a reference for this one sentence from the poster?  "This
has been used several studies to calculate summary statistics ( CITATIONS
)." This is the only sentence I found that has a flag for needing a
reference.  And for reference formatting, should I just have \ref{reference
number}​?

Thanks

**Comment by rossibarra** [comment]
There are example references in the latex, with formatting at the end.
There are several spots that need the refs filled in in the references
(these appear as ?? in the pdf), including stuff on gluma.  Format should
follow the first four numbered ones (no title).

-Jeff

---

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org
