### ISSUE TITLE
logos

### ISSUE THREAD

**Issue by rossibarra** [rossibarra/angsdwrapper-poster#2]
I'm OK with the cornkey. But we could also do a UCD logo, dept. plant sciences logo, CPB logo, whatever.  These are specified in the beamerthemesharelatex.sty file .

**Comment by arundurvasula** [comment]
Cornkey works for me too! Do we just rename it as logo.png?

**Comment by rossibarra** [comment]
nope, already did that in the file.

**Comment by arundurvasula** [comment]
This can be closed then right?

**Comment by tvkent** [comment]
Can we do one cornkey and one plant sciences?  Or even better, one cornkey and one picture of Jeff as Mendel?

**Comment by arundurvasula** [comment]
Agree with one cornkey and one plant science. I'd say plant science in top left corner.

**Comment by rossibarra** [comment]
Sounds good.

---

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by SidBhadra-Lobo** [comment]
Plant Sciences, adjusted for size, is on the top left now.
